default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace   # remove trailing whitespaces
      - id: end-of-file-fixer     # empty line at EOL
      - id: check-yaml
      - id: check-added-large-files # block large files

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args:
          - --strict
          - --scopes
          - alu,lsu,fpu,mul,div,core

  - repo: local
    hooks:
    - id: check-license
      name: Check license headers
      entry: python scripts/check_license.py
      language: python
      files: \.(sv|v|svh|vh|py)$
      exclude: ^vendor/

    - id: verible-format
      name: Verible verilog format
      entry: verible-verilog-format
      language: system
      types_or: [verilog, system-verilog]
      args: [--flagfile, .rules.verible_format, --inline]

  - repo: local
    hooks:
    - id: verible-lint
      name: Verible verilog lint
      entry: verible-verilog-lint
      language: system
      types_or: [verilog, system-verilog]
      args: [--rules_config, .rules.verible_lint]
