[project]
site_name = "Crab Docs"
site_description = "Pulsar-V Crab Core specification for RISC-V RV64GC"
site_author = "AGH Logic Unit"
copyright = "Copyright &copy; <year> AGH Logic Unit"
extra_javascript = [
    "javascripts/mathjax.js",
    "https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js",
]

[project.theme]
variant = "modern"
palette.scheme = "slate"
palette.primary = "deep orange"
palette.accent = "orange"
features = ["navigation.expand", "navigation.sections", "navigation.path"]


[project.markdown_extensions.admonition]
[project.markdown_extensions.tables]
[project.markdown_extensions.pymdownx.blocks.caption]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.arithmatex]
generic = true
[project.markdown_extensions.def_list]
[project.markdown_extensions.pymdownx.tasklist]
custom_checkbox = true
[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.snippets]
[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
    { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" },
]
[project.markdown_extensions.pymdownx.emoji]
emoji_index = "zensical.extensions.emoji.twemoji"
emoji_generator = "zensical.extensions.emoji.to_svg"
